export const configuration = {
    about: {
        drive: 'success',
        heading: 'How We Help You To Sell Your Product',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,dolore magna aliqua. Ut enim ad minim veniam!',
        services: [
          {icon: 'html5', name: 'HTML5 & CSS3', excert: 'Id porro tritani recusabo usu, eum intellegam consequuntur et. Fugit de', } ,
          {icon: 'bolt', name: 'Easy to use', excert: 'Id porro tritani recusabo usu, eum intellegam consequuntur et. Fugit de', } ,
          {icon: 'tablet', name: 'Fully Responsive', excert: 'Id porro tritani recusabo usu, eum intellegam consequuntur et. Fugit de', } ,
          {icon: 'rocket', name: 'Parallax Effect', excert: 'Id porro tritani recusabo usu, eum intellegam consequuntur et. Fugit de', } ,
        ]
    },
    clients: {
        drive: 'Trust',
        heading: 'Companies who use our services',
        description: 'Lorem ipsum dolor sit amet, smod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam!',
        companies: [
          {name: 'company1' , logo: 'company-logo1.png'},
          {name: 'company2' , logo: 'company-logo2.png'},
          {name: 'company3' , logo: 'company-logo3.png'},
          {name: 'company4' , logo: 'company-logo3.png'},
          {name: 'company5' , logo: 'company-logo4.png'},
          {name: 'company6' , logo: 'company-logo5.png'},
          {name: 'company7' , logo: 'company-logo6.png'},
          {name: 'company8' , logo: 'company-logo8.png'},
          {name: 'company9' , logo: 'company-logo9.png'},
        ],
    },
    footer: {
        copyrightText: 'Made with love by',
        developer: 'AdMISTER.IN',
        developerLink: 'http://admister.in',
    },
    galleryImages: [
        'gallery-image-1.jpg',
        'gallery-image-2.jpg',
        'gallery-image-3.jpg',
        'gallery-image-4.jpg',
        'gallery-image-5.jpg',
        'gallery-image-6.jpg',
        'gallery-image-1.jpg',
        'gallery-image-2.jpg',
        'gallery-image-3.jpg',
    ],
    header: {
      heading: 'Hi there ',
      title: 'Champ',
      tagline: 'We are just getting started',
      ctaText: 'Let\'s Get Started',
      ctaLink: 'home',
      background: 'assets/images/banner-images/banner-image-2.jpg',
    },
    page: {
        title: 'welcome to my world',
        logo1: 'logo.png',
        logo2: 'logo-2.png',
    },
    pricing: {
    drive: 'Your choice',
    heading: 'We Have the Right Package for You',
    description: 'this is some description',
    businessPlan: [
                  {heading: 'Personal',
                  targetUsers: 'The standard version',
                  currency: '₹',
                  price: 19,
                  description: 'For the whole team',
                  offerings: ['5 Downloads', '2 Extensions', 'Tutorials', 'Forum Support', '1 year free updates'],
                  ctaLink: '#',
                  ctaButtonText: 'BUY TODAY',
                  featured: false},
                  {heading: 'Student',
                  targetUsers: 'Most popular choice',
                  currency: '₹',
                  price: 29,
                  description: 'For the whole team',
                  offerings: ['15 Downloads', '5 Extensions', 'Tutorials with Files', 'Forum Support', '2 year free updates'],
                  ctaLink: '#',
                  ctaButtonText: 'BUY TODAY',
                  featured: true},
                  {heading: 'Business',
                  targetUsers: 'For the whole team',
                  currency: '₹',
                  price: 49,
                  description: 'For the whole team',
                  offerings: ['Unlimited Downloads', 'Unlimited Extensions', 'HD Video Tutorials', 'Chat Support', 'Lifetime free updates'],
                  ctaLink: '#',
                  ctaButtonText: 'BUY TODAY',
                  featured: false},
                  ]
    },
    users: [
      {comments: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ulaboreet dolore magna aliqua',
      name: 'John Doe',
      photo: 'user-1.jpg', },
      {comments: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ulaboreet dolore magna aliqua',
      name: 'Roslyn Doe',
      photo: 'user-2.jpg', },
      {comments: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ulaboreet dolore magna aliqua',
      name: 'Jon Doe',
      photo: 'user-3.jpg', },
    ]
    };
